# TYPO3 Crowdin Integration
# This extension is part of the TYPO3 translation project: https://crowdin.com/project/typo3-cms
# Translations are managed centrally - no project credentials needed
#
# Official documentation: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/TranslationServer/Crowdin/
#
# Configuration syntax updated to TYPO3 standards (2024):
# - preserve_hierarchy: Prevents language code from being used as base directory
# - Absolute paths with leading slashes (/)
# - %original_path% and %original_file_name% placeholders for correct file placement
# - ignore: Excludes existing translation files from re-translation

preserve_hierarchy: 1

files:
  - source: /Resources/Private/Language/*.xlf
    translation: /%original_path%/%two_letters_code%.%original_file_name%
    ignore:
      - /**/%two_letters_code%.%original_file_name%
